### ISSUE TITLE
an unknown tool name found in scoped lint: `rustdoc::all`

### ISSUE THREAD

**Issue by tuddman** [avitex/rust-public-ip#13]
when attempting to include `public_ip = "0.2"` in `Cargo.toml`

```
error[E0710]: an unknown tool name found in scoped lint: `rustdoc::all`
  --> <Home>/.cargo/registry/src/github.com-1ecc6299db9ec823/public-ip-0.2.1/src/lib.rs:24:5
   |
24 |     rustdoc::all,
   |     ^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0710`.
error: could not compile `public-ip`

```

ref:  https://doc.rust-lang.org/rustdoc/lints.html

**Comment by avitex** [comment]
Out of curiosity, what toolchain do you have setup and version of rustc?

[`rustdoc::all`](https://github.com/rust-lang/rust/commit/45229b0777e6791625392529c2c9d8eceac28dbd) was introduced in `1.52` 

```
cargo --version
rustc --version
```

Perhaps if rustdoc is not installed, this lint will fail.

**Comment by avitex** [comment]
I've put the lint behind a `cfg`. Closing as this should be fixed in the latest release
