### ISSUE TITLE
Picking IPv4 & IPv6 addresses

### ISSUE THREAD

**Issue by MOZGIII** [avitex/rust-public-ip#8]
It would be great if this crate allowed picking the IP protocol version to resolve: IPv4/IPv6/Any.
On the dual-stack system, the hyper's happy eyeball protocol kicks in, and the resulting addresses are unpredictable.

**Comment by avitex** [comment]
I'll have a look this weekend, this is a good feature to have. Need to have a new release with tokio v1 anyway.
