### ISSUE TITLE
How to get an error message ein case of failure?

### ISSUE THREAD

**Issue by aWeinzierl** [avitex/rust-public-ip#9]
I use the resolver the basic way. 
The resolver works in principal. 
However the resolver fails to return an IP-address (i.e. returns None) on a different environment.

Is there a way to view what went wrong?

Environment 1: Windows 10 Pro
Environment 2: WSL2 (Ubuntu 18.04

**Comment by avitex** [comment]
Heya @aWeinzierl,

I'm about to release a new version that improves error messages but the way to know what went wrong will be the same. Essentially a resolver/group of resolvers returns a resolution stream. When resolving a single address, any error a resolver returns is ignored and it attempts the next resolver. If you want to see what's going wrong then you'll need to pickup each error that happens from the stream. Enough text, now for an example:

```rust
use futures_util::{future, StreamExt, TryStreamExt};
use public_ip::{self, dns, http, Version};

#[tokio::main]
async fn main() {
    // List of resolvers to try and get an IP address from.
    let resolver = &[
        http::HTTP_WHATISMYIPADDRESS_COM_RESOLVER,
        dns::GOOGLE_DNS_TXT_RESOLVER,
    ];
    let addr = public_ip::resolve_stream(resolver, Version::Any)
        // For each error in the stream we print it out to STDERR (console).
        .inspect_err(|err| eprintln!("resolver error: {}", err))
        // We filter out the errors and leave just the resolved addresses in the stream.
        .filter_map(|result| future::ready(result.ok()))
        // We get the first resolved address in the stream.
        .next()
        // Wait for the future to finish.
        .await
        // We remove the details of the resolution if we don't care about them.
        .map(|(addr, _details)| addr);

    dbg!(addr);
}
```

**Comment by avitex** [comment]
You can try this example now at https://github.com/avitex/rust-public-ip/blob/master/examples/errors.rs
